name: Deploy HalalChain Marketplace

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Update and upgrade system
      run: |
        sudo apt update && sudo apt upgrade -y
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci || npm install
      
    - name: Fix CSS issues
      run: |
        if grep -q "font-poppins" src/app/globals.css; then
          sed -i 's/font-poppins/font-sans/g' src/app/globals.css
          echo "Fixed font-poppins references in globals.css"
        fi
    
    - name: Build
      run: |
        npm install qrcode.react@latest react-syntax-highlighter@latest --save
        npm run build
      env:
        CI: false
        NEXT_PUBLIC_APP_VERSION: ${{ github.ref_type == 'tag' && github.ref_name || 'development' }}
        NEXT_PUBLIC_COMMIT_SHA: ${{ github.sha }}
    
    - name: Run tests
      run: |
        if [ -f package.json ] && grep -q '"test":' package.json; then
          npm test
        else
          echo "No tests specified"
        fi
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: .next/
        retention-days: 7

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' || startsWith(github.ref, 'refs/tags/v') }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-output
        path: .next/
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Extract version
      id: extract_version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
        else
          VERSION=latest
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          halalchain/marketplace:latest
          halalchain/marketplace:${{ steps.extract_version.outputs.VERSION }}
          halalchain/marketplace:${{ github.sha }}
        build-args: |
          APP_VERSION=${{ steps.extract_version.outputs.VERSION }}
          BUILD_TIMESTAMP=${{ steps.extract_version.outputs.TIMESTAMP }}
        cache-from: type=registry,ref=halalchain/marketplace:latest
        cache-to: type=inline
    
    - name: Deploy to production
      run: |
        echo "Deploying version ${{ steps.extract_version.outputs.VERSION }} to production server..."
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
        ssh -o StrictHostKeyChecking=accept-new ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "cd ${{ secrets.DEPLOY_PATH }} && \
          docker-compose pull && \
          docker-compose up -d" || {
            echo "::error::Deployment failed. Check SSH connection and server status."
            exit 1
          }
        echo "Deployment complete!"
      env:
        DEPLOY_VERSION: ${{ steps.extract_version.outputs.VERSION }}

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Extract version info
      id: version_info
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
          IS_RELEASE=true
        else
          VERSION="development build"
          IS_RELEASE=false
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "IS_RELEASE=$IS_RELEASE" >> $GITHUB_OUTPUT
    
    - name: Send Slack notification
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "text": "New deployment completed!",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "✅ Deployment Successful",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Project:*\nHalalChain Marketplace"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Version:*\n${{ steps.version_info.outputs.VERSION }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Deployed by:*\n${{ github.actor }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Environment:*\nProduction"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "🚀 <https://halal-chain.com|View Live Site> | <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Run>"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: ${{ success() && vars.SLACK_WEBHOOK_URL != '' }}